import type { Metadata } from "next";
import "@/styles/globals.css";
import Navbar from "@/components/Navbar";
import { Poppins } from "next/font/google";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

const poppins = Poppins({
   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
   subsets: ["latin"],
   display: "swap",
});

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" className={poppins.className}>
         <body className="bg-[#121212] text-white">
            <Navbar />
            <main>{children}</main>
         </body>
      </html>
   );
}
